services:
  - type: web
    name: oratorio-backend
    runtime: docker
    repo: https://github.com/ilreleonecdc/oratorio-backend
    branch: main
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/oratorio-backend.dll
